version: '3' # esta es la version de la api

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./objects:/objects
      - ./structure:/structure
      - ./backup:/backup
    ports:
      - "3306:3306"
