version: '25082024'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
    # - ./mysql:/var/lib/mysql
      - ./objects:/objects
      - ./structure:/structure
      - ./backup:/backup
    ports:
      - "3306:3306"
